### ISSUE TITLE
CSS framework?

### ISSUE THREAD

**Issue by infernocloud** [openwichita/lake-afton-website#1]
Let's pick which CSS framework we should use. I like both Bootstrap and Foundation. I worked with Foundation most recently because it used Sass but Bootstrap is using Sass now. There are also some minimal frameworks that could be interesting to experiment with.

- [ ] Bootstrap
- [ ] Foundation
- [ ] http://www.basscss.com/
- [ ] https://milligram.github.io/
- [ ] http://purecss.io/

**Comment by jarrettgreen** [comment]
+1 For bootstrap.
