### ISSUE TITLE
Convert website from php to a static site generator

### ISSUE THREAD

**Issue by infernocloud** [openwichita/lake-afton-website#2]
Either in node.js, ruby, or go.

Must include full setup, develop, and run instructions to be merged in.

**Comment by infernocloud** [comment]
Note: The current live website exists in the "just-get-it-done-php" branch, not master.

**Comment by jameskolce** [comment]
I could help with this!

**Comment by jameskolce** [comment]
@infernocloud The website is ready here: https://github.com/jameskolce/lake-afton-website/tree/static-site how do you want to proceed? Maybe creating a gh-pages branch would be ideal, then I can make a pull request there, what do you think?

**Comment by infernocloud** [comment]
Very awesome, thank you! I'll make that branch and then this weekend I'll test your pull request and merge it in if it goes smoothly on my local environment.

**Comment by infernocloud** [comment]
https://github.com/openwichita/lake-afton-website/tree/gh-pages

**Comment by jameskolce** [comment]
Alright! Pull request sent. Let me know how that works or if you have any issue.
