### ISSUE TITLE
Add page for sponsors

### ISSUE THREAD

**Issue by infernocloud** [openwichita/lake-afton-website#3]

**Comment by southekal** [comment]
@infernocloud - is the goal to have a separate /sponsors url path with this list?

- Callcap
- Signlab
- Terracon Foundation

If you have logos of these sponsors please send it my way, else I will look it up from their website.

**Comment by infernocloud** [comment]
Hey! The current "Who we are" page lists these sponsors for right now. https://www.lakeafton.com/who-we-are/ You could probably grab the logos from their linked websites and work them into that page for a quick update.

When adding this a year ago I think we expected the Observatory board would more actively look for new sponsors and so we would want to display some info on existing sponsors and information on new sponsors joining. I'm not sure what the board of directors thinks about new sponsors anymore. @DJSethDuncan thoughts on this one?

**Comment by DJSethDuncan** [comment]
Yeah I don't think we're gonna go with a single page for sponsors at the moment. If we outgrow the Who we Are page, we'll reconsider. Thanks!
