### ISSUE TITLE
Add page for observatory board of directors and advisors

### ISSUE THREAD

**Issue by infernocloud** [openwichita/lake-afton-website#4]

**Comment by imacrayon** [comment]
Is there content/images for this page anywhere?

**Comment by infernocloud** [comment]
No there isn't currently. @DJSethDuncan Do you guys want a page like this on the website? If so can you guys put together some info to display and maybe include a group photo or something?

**Comment by DJSethDuncan** [comment]
Nah, I don't think we want to do this for now. Thanks though!
